// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ENSReverse: typeof import('./src/components/ENSReverse.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Votes: typeof import('./src/components/Votes.vue')['default']
    WalletConnectionButton: typeof import('./src/components/WalletConnectionButton.vue')['default']
  }
}
